### ISSUE TITLE
Master branch is not stable. 

### ISSUE THREAD

**Issue by samir-dahal** [adamfoneil/ModelSync.UI#34]
I saw your post on upwork. I cloned the repo to try it out but the master branch has errors.

Namesapce
```
ModelSync.App.Controls
```
Class
```
ObjectTypeNode
```
![image](https://user-images.githubusercontent.com/39849021/183401111-5a9391c3-dd6f-484a-8cd8-4e3ccaea5761.png)

**Comment by adamfoneil** [comment]
thank you @samir-dahal . In the ModelSync repo (it looks like you must've cloned that), make sure you have the `db-to-db-improvements` branch checked out. This relates to ModelSync [issue 16](https://github.com/adamfoneil/ModelSync/issues/16)
